title: Dan Raloff's Development Log
description: >
  Here's where I write about what I'm learning for past and future me
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://komon.xyz" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Daniel Raloff
author-img: daniel-raloff_100.jpg
about-author: I am a Staff Engineer currently @ Fountain.
social-twitter: draloff
social-github: KOMON
social-linkedin: daniel-raloff
social-email: dan@raloff.net

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
